print("A feather floats through the air. The falling feather.")
print(" ")
print("A city, Savannah, is revealed in the background. The feather ")
print("floats down toward the city below. The feather drops down ")
print("toward the street below, as people walk past and cars drive ")
print("by, and nearly lands on a man's shoulder.")
print(" ")
print("He walks across the street, causing the feather to be whisked ")
print("back on its journey. The feather floats above a stopped car.")
print("The car drives off right as the feather floats down toward ")
print("the street.")
print(" ")
print("The feather floats under a passing car, then is sent flying")
print("back up in the air. A MAN sits on a bus bench. The feather ")
print("floats above the ground and finally lands on the man's ")
print("mudsoaked shoes")
print(" ")
print("The man reached down and picks up the feather. His name is ")
print("FORREST GUMP. He looks at the feather oddly, moves aside a ")
print("box of chocolates from an old suitcase, then opens the case.")
print(" ")
print("Inside the old suitcase are an assortment of clothes, a ")
print("pingpong paddle, toothpaste and other personal items.")
print(" ")
print("Forrest pulls out a book titled  Curious George, then places ")
print("the feather inside the book. Forrest closes the suitcase.")
print(" ")
print("Something in his eyes reveals that Forrest may not be all ")
print("there.")
print(" ")
print("Forrest looks right as the sound of an arriving bus is heard.")
print("A bus pulls up. Forrest remains on the bus bench as the bus")
print("continues on.")
print(" ")
print("A BLACK WOMAN in a nurse's outfit steps up and sits down at ")
print("the bus bench next to Forrest. The nurse begins to read a ")
print("magazine as Forrest looks at her.")
print(" ")
print("                                     FORREST")
print("                         Hello. My name's Forrest Gump.")