a = input("Who are you? ")
b = input("What do you hate most? ")
c = input("What are you holding? ")
d = input("Where do you live ")
e = input("Pick a number ")
f = input("What do you want most ")
print("it's a beautiful summer day")
print("you are " + a + " and our living at " + d)
print("As you relax the inpossible happens")
print(e + " of your worst enemy " + b + " show up")
print("You're caught off guard and you're not prepared for the fight to come ")
print("but at that moment you realize you're holding on to " + c)
print("this makes you ready to fight")
print("you fight off your worst enemy yet after it and eventually you win")
print("in the ruins of " + d + " and the corpses of " + b)
print("you find the thing that you've always wanted ")
print("you fined a " + f + " and you live happily ever after ")